projects:
  Block API:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: pfgyu7uys5b5ddgk6zf7w342iu
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
      endpoints:
        prod: >-
          https://yokymsstbzdjjn62yhvcymkueu.appsync-api.us-east-1.amazonaws.com/graphql
